## HW1: Regex, wordnet

In [8]:
import re
from nltk.corpus import wordnet as wn
from nltk import download

download('wordnet')
download('omw-1.4')

[nltk_data] Downloading package wordnet to /home/rehan/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/rehan/nltk_data...


True

In [13]:
# opening a file

with open('BERT-vocab.txt', encoding='utf8') as bert_f:
    bert_vocab = [w.strip() for w in bert_f]  ## List Comprehension. Very useful!

In [ ]:
## Don't do this. Not pythonic!

bert_vocab = []

with open('BERT-vocab.txt', encoding='utf8') as bert_f:
    for line in bert_f:
        bert_vocab.append(line.strip())

In [14]:
# wordnet as "dictionary"
wn_words = set(wn.words())

In [16]:
print("BERT vocab len:", len(bert_vocab))
print("Wordnet vocan len:", len(wn_words))
print("BERT proper words:", len(wn_words.intersection(bert_vocab)))

BERT vocab len: 30522
Wordnet vocan len: 147306
BERT proper words: 14510


In [26]:
## Filtering BERT Vocab with

unused_words = [w for w in bert_vocab if '[unused' in w]
print('Unused Words len:', len(unused_words))
special_words = [w for w in bert_vocab if w.startswith('[') and w not in unused_words]
print('Special words len:', len(special_words))
hash_words = [w for w in bert_vocab if w.startswith('#')]
print('Hash words len:', len(hash_words))

## etc

Unused Words len: 994
Special words len: 6
Hash words len: 5829


## HW2: Pytorch, spaCy

In [39]:
import torch
import spacy

def scaling(X: torch.Tensor):
    ## wrong:
    scaled_X_wrong = (X - torch.min(X))/(torch.max(X) - torch.min(X))
    ## correct:
    scaled_X = (X - torch.min(X, dim=0).values)/(torch.max(X, dim=0).values - torch.min(X, dim=0).values)
    return scaled_X_wrong, scaled_X

x = torch.FloatTensor([[5, 1, 2], [3, 1, -1], [-1, 0, 6]])
print(x)
scaling(x)

tensor([[ 5.,  1.,  2.],
        [ 3.,  1., -1.],
        [-1.,  0.,  6.]])


(tensor([[0.8571, 0.2857, 0.4286],
         [0.5714, 0.2857, 0.0000],
         [0.0000, 0.1429, 1.0000]]),
 tensor([[1.0000, 1.0000, 0.4286],
         [0.6667, 1.0000, 0.0000],
         [0.0000, 0.0000, 1.0000]]))

## HW3: Viterbi, Training Loop